kind: ENC[AES256_GCM,data:QZWXBQ2Y,iv:cFqgwAvLqJ6U9TYxTJ2M+DgIIWFLRWK7lP6jlmkd2+g=,tag:i7WTCJM7FFedscMC0fyY6g==,type:str]
ansible_user: ENC[AES256_GCM,data:gcAZhSGa9g==,iv:+03kd+L69855M/qcr8RyvqJbowaF+xn/0GCQDVyUb10=,tag:8FqmuzXxqe5ECtKs+DAhyA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:6tqDPClloskUcV0=,iv:ujeREa8EbEpHhNt9vOOdHQzdD07vcJN9Dw8BcRQ0dp4=,tag:Y6PKpoGd6FUvpWJNapCXJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rg5gz0nx5ld88mrtpxvqzz5t4a807u3hn92a0lejv94t2vfge5qsyp8ywy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VDFTeW02T1NaYUJaUWdX
            MGJpNk95bHdiUVNmQTNDTkRJcUF4dHNqWVdBCnJtS2FFSDZoRFJTSzVtdXk1T0NH
            ZThZdjRmODIzdmdaQzZtcklGbkRmNlUKLS0tIGlicEdYWnBwZkVUUExIem5iTk5a
            SThaakpINFZxL3NQUExFdWR6T0xpNkkKIGArYX6p6gA/0ky6rgcO7Rv9x/rnTwao
            NxkF05enl4/Vr4SSdTRrcJsXLwO7vHkjVz0q4116wQBbImHb9LwDNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-28T18:11:46Z"
    mac: ENC[AES256_GCM,data:clI40mcWmP0WyufLWm5J5GG6+YkO3dy4rATsJ3+QFtqv5JP3Rhjbr+nP1FewgrgsiZGBFrAtl/xTtB+HGMGqG7JZFrvqreyQdBb6C/gw75O8d1IRwViFcS5Pw0wul9RKYwlq0K8upebCF+8QTHuu/Xtm71nKQ6c4EEPO+4hhBy8=,iv:VEB9QE+/DNgDzg39hRBmuWuYRHH017WmCykZ/DH404w=,tag:8gPPYyN004vgxNzIbWDlNg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
