apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:bcY3N74VM721rXapL3CpP7XhtkNK8Xk+Ck4coNjUVXSqchBgjBF0ng==,iv:1VaQKndUyOGjB6wmfrFSjAkHjHqiODSumwct3ID3Sj0=,tag:gj9K3SBzMsdPHzfAnRPPXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rg5gz0nx5ld88mrtpxvqzz5t4a807u3hn92a0lejv94t2vfge5qsyp8ywy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY0M2ZHZ3WnRTNXlQVU1J
            RWVnRHI0TXRGQWs5anhJb3phU255bkYzaVVjCjNxZWI3aWQ3Y2laRnB1bVJUNE9m
            ZGluRjErM2hxM2ZYWW1QQUVSRTZKeHMKLS0tIG9RQnlMR1dOdEJjZ1pDMjRNU3Bn
            SEtZV2tWZjNOOGQ2NGdvY2FBZHQ0Y2MKXI49fLIOWhKCvNdRgL0SymCr4PsguHDP
            asFLj1FlDAFzXoZuSVQNdubTyL7gmXl7uDdrg750xq8WRbV30ZoNyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-28T17:16:39Z"
    mac: ENC[AES256_GCM,data:BO/rVYyeAqcT6KZqam4NIIr1pZstpLZUqirzQwpTIkAWpztRsQDPtiTQCOTPyu38bjRxn7H4LG9zuIeYEm0fXr8QnvnRjF5rTyNLILQjO2e/zJ8dpS+Xla3IUMckN/8+lHEWrCUlpovifEcMqCRldyGvpD6Lqp7USuyI8xHcqNg=,iv:rRET+2GjSYSht0M9OXNvS5cOMlfEXjYVMvHP32a6g3w=,tag:eSREQT6U3ifkfSuwG54mrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
