apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:BiRw/EQuPFARTumDsIPlavjzuDVK9Uw69hSXFBPTeIQW8D7QngAHsA==,iv:JXFWkkvWZ1k1QPOwX6x+usV/Yt1ZPA9dV8w1GsYnE1E=,tag:d01E7hFLbHQB5BxjWFco+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rg5gz0nx5ld88mrtpxvqzz5t4a807u3hn92a0lejv94t2vfge5qsyp8ywy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTmJnMmVkS3hVUjNNYVBZ
            WGtQT2VqTXRpNURwWGp0WmVFNFlkNVU1WmpjCnRzdHR5KzB6RmZVdExsMWE3NEVu
            TmcwVzl3NkZIVis5Vm1PeGVveUYxMXcKLS0tIDJOa0FHVXZVS0Z4VEtVUlVla2VQ
            Y1lBaHV0cWZOMk5tY1lUQmM3M2dVWm8KLRn3pMmcHC4Fu9L00w+ZvObTVGLaJ4MH
            t1AQfTROsGe2KIYcavhDoiQ/VPDtTQmiRzcdTdAKNDXR2L3It5Rd3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-28T18:11:46Z"
    mac: ENC[AES256_GCM,data:VntLJJz9s+eWpQzXTmRw53fH7RhF+5i9SvEO9u8pmbO+g8OISyW6w/ZcRB5XDoMJg1fWhJjTTMXFDse8D+OVawF9pPIplCPc698qhZOvogwyUv3LAPciSPF4O7Mteal2mMSKtqlwcj4cNiREzmI5gnWA+YlAFeuxnsu6Z0/W5jU=,iv:rqZtl1cYlQDXjwMklt5rYpzqChUYmV5vPwSY7i8hP7c=,tag:5JfuwW7omGkZlhD89bAgHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
