---
kubernetes:
  children:
    master:
      hosts:
        k3s-master-0:
          ansible_host: 10.10.0.200
    worker:
      hosts:
        k3s-node-1:
          ansible_host: 10.10.0.201
        k3s-node-2:
          ansible_host: 10.10.0.202
        k3s-node-3:
          ansible_host: 10.10.0.203
