apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:xpCUkZkOf8scU1GVHTOVbvNPYgBPcrv5dQ==,iv:+cYxFhuXVEUPtyaXREcncIT0KBYAzIq+X8jT2zslUm0=,tag:Ns6gcFGZ/A6wYwfUjNaZ5g==,type:str]
    api-key: ENC[AES256_GCM,data:j8ed9nHl+12vUSqxaZb5D4N//R1pXHpk4vHqF/8cd8ucut3m7A==,iv:sTCRiC7OrhN14NpIcaHYZ25+HZVC4oG2qbfPWg63KmI=,tag:w35bnkS2ox1LUF1S0WiT5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rg5gz0nx5ld88mrtpxvqzz5t4a807u3hn92a0lejv94t2vfge5qsyp8ywy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMXdTc3VabFl0Y1RQcHRj
            MWtPMFo0ZUFRZ1R2UkZWakFtUytPMEVhRG00CjByblZCV2ZOZmhLa1pTRkdFOUVK
            YkRUeVI0anZJVTJtSG1nanVITU4zQ1kKLS0tIC9pZVkwVmQ0c1VFSDNWM3JxSUJH
            dURNaHdJcTBSUyt0S1hjRE5qWlg5bncKz7gQccpw5JluRXcD4F4NeGaK+xEOHz6v
            fIpN90OlXvJ19Jyu+oQhKQkoCHk7EC+wQDyZ/bOVHzy+9qWXIInu/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-28T18:11:46Z"
    mac: ENC[AES256_GCM,data:L4b1r+uo8Sh/SJMeJpkA64gH7uUfLFUrQhDdvG4EWzz1FLZA5kRvd2qn5umismVnIh38kEiG59zdRXZcbZZlWV64p2J2qFsWHfyjxsAndtseSqJpERgQxEsPXBXyd/nywA9FIrX49zYFLRkXHYTHGTWxchQhj5pdZKehdCGiTXQ=,iv:dav9Iqh8Op7VgknVFNJYYjyvNd7qgh1QRINeFqbDCfM=,tag:2D55GCejkcwQPJR6NWr9ng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
