---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Berlin"
  METALLB_LB_RANGE: "10.10.0.210-10.10.0.220"
  METALLB_K8S_GATEWAY_ADDR: "10.10.0.210"
  METALLB_INGRESS_ADDR: "10.10.0.211"
